google.application.name=Tbibi Medical App
google.credentials.path=config/google_credentials.json
google.calendar.scopes=https://www.googleapis.com/auth/calendar,https://www.googleapis.com/auth/calendar.events 